language: android
install:
  - echo y | sdkmanager 'ndk-bundle'
  #- echo y | sdkmanager 'cmake;3.6.3155560'
  - export ANDROID_HOME=$HOME/android/sdk
  - export ANDROID_NDK_HOME=$HOME/android/sdk/ndk-bundle
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.0

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-android-17
  before_install:
    -exit 1
    - echo Superhero incoming
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.tar.gz
    - tar -xzvf apache-ant-1.10.1-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.1/bin:$PATH
    - echo Antman is $(ant -version)
    - yes | sdkmanager "platforms;android-28" 1>/dev/null 2>/dev/null
    - sdkmanager "platform-tools" "build-tools;23.0.1" "cmake;3.6.4111459" "ndk-bundle" "platforms;android-21" "platforms;android-23" "extras;android;m2repository" "extras;google;m2repository"
    - fuse install android
  script:
    - ./gradlew build --scan -s
