language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.0

    # The SDK version used to compile your project
    - ndk-bundle
    - android-21
    - android-23
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28
    - sys-img-armeabi-v7a-android-17
before_install:
#  - echo Superhero incoming
#  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.tar.gz
#  - tar -xzvf apache-ant-1.10.1-bin.tar.gz
#  - export PATH=`pwd`/apache-ant-1.10.1/bin:$PATH
#  - echo Antman is $(ant -version)
  - android list sdk --no-ui --all --extended
  - echo -e '### User Sources for Android SDK Manager\n#Fri Nov 03 10:11:27 CET 2017 count=0' > $HOME/.android/repositories.cfg
  - cd $HOME
  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O $HOME/android-sdk.tgz
  - mkdir android
  - unzip android-sdk.tgz -d android/sdk
  - export PATH=$PATH:$HOME/android/sdk/tools:$HOME/android/sdk/tools/bin
  - cd -
  - echo y | sdkmanager "platforms;android-21"
  - echo y | sdkmanager "platforms;android-23"
  - echo y | sdkmanager "platforms;android-28"
  - echo y | sdkmanager "platform-tools"
  - echo y | sdkmanager "build-tools;28.0.0" 
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "extras;android;m2repository"
  - echo y | sdkmanager "extras;google;m2repository"
#  - yes | sdkmanager "platform-tools" "build-tools;23.0.1" "cmake;3.6.4111459" "ndk-bundle" "platforms;android-21" "platforms;android-23" "extras;android;m2repository" "extras;google;m2repository"
  - export ANDROID_HOME=$HOME/android/sdk
  - export ANDROID_NDK_HOME=$HOME/android/sdk/ndk-bundle
script:
  - echo y | ./gradlew build --scan -s
